# Generated by Django 3.1.3 on 2020-12-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
