# Generated by Django 3.1.3 on 2020-12-22 11:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201222_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile/images'),
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
